apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
        - name: expense-tracker
          image: ghcr.io/ripisopol/expense-tracker:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /app/data     
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: expense-secret
                  key: SECRET_KEY
            - name: DB_PATH
              value: "/app/data/expense.db"
      volumes:
        - name: data
          hostPath:
            path: /data/expense
            type: DirectoryOrCreate   